services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_HOST=0.0.0.0
      - NODE_ENV=development
      - VITE_API_URL=https://clubpage-api-env.eba-rstfvjmj.us-west-1.elasticbeanstalk.com
    command: npm run dev
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - ./backend/uploads:/app/uploads
    environment:
      - MONGO_URI=mongodb+srv://kattsyna:yu7SdJsrY6kahmIK@cluster0.e5qd8g7.mongodb.net/clubpage?retryWrites=true&w=majority&appName=Cluster0
      - PORT=8080
      - NODE_ENV=development
      - CORS_ORIGIN=https://clubpage.pages.dev
      - JWT_SECRET=your_secret_key_here
      - BASE_URL=https://clubpage-api-env.eba-rstfvjmj.us-west-1.elasticbeanstalk.com
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 1.1.1.1
networks:
  app-network:
    driver: bridge

volumes:
  frontend_node_modules:
  backend_node_modules: