services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_HOST=0.0.0.0
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm run dev
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/clubpage
      - PORT=8080
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:5173
      - JWT_SECRET=your_secret_key_here
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  frontend_node_modules:
  backend_node_modules: