version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=https://clubpage.pages.dev/api
    command: npm run dev
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - ./backend/uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - BASE_URL=https://clubpage.pages.dev
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    command: npm run dev

networks:
  app-network:
    driver: bridge

volumes:
  frontend_node_modules:
  backend_node_modules: